# fly.toml file generated for weatherbot on 2022-08-26T19:11:47+03:00

app = "weatherbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
